import type { editor } from "monaco-editor";

export const workspaceMonacoThemeLight = "vitesse-light";
export const workspaceMonacoThemeDark = "vitesse-dark";

const vitesseLightRules: editor.ITokenThemeRule[] = [
  { token: "keyword.operator", foreground: "ab5959" },
  { token: "keyword", foreground: "8f8e8a" },
  { token: "constant.language.boolean", foreground: "8f8e8a" },
  { token: "constant.language", foreground: "8f8e8a" },
  { token: "constant.numeric", foreground: "2f798a" },
  { token: "constant", foreground: "a65e2b" },
  { token: "string.regexp", foreground: "ab5e3f" },
  { token: "string.comment", foreground: "a0ada0" },
  { token: "string", foreground: "b56959" },
  { token: "support.type.builtin", foreground: "ab5959" },
  { token: "support.type", foreground: "2e8f82" },
  { token: "support.constant", foreground: "a65e2b" },
  { token: "support", foreground: "998418" },
  { token: "storage.type", foreground: "ab5959" },
  { token: "storage", foreground: "ab5959" },
  { token: "entity.name.function", foreground: "59873a" },
  { token: "entity.name.tag", foreground: "8f8e8a" },
  { token: "entity.name.type", foreground: "2e8f82" },
  { token: "entity.name", foreground: "59873a" },
  { token: "entity.other.attribute-name", foreground: "b07d48" },
  { token: "variable.language", foreground: "a65e2b" },
  { token: "variable", foreground: "b07d48" },
  { token: "type.identifier", foreground: "5a6aa6" },
  { token: "type", foreground: "2e8f82" },
  { token: "attribute.value", foreground: "b56959" },
  { token: "attribute.name", foreground: "998418" },
  { token: "meta.property-name", foreground: "998418" },
  { token: "meta.object-literal.key", foreground: "998418" },
  { token: "meta.module-reference", foreground: "8f8e8a" },
  { token: "property", foreground: "998418" },
  { token: "namespace", foreground: "b05a78" },
  { token: "delimiter.bracket", foreground: "999999" },
  { token: "delimiter", foreground: "999999" },
  { token: "operator", foreground: "ab5959" },
  { token: "tag", foreground: "8f8e8a" },
  { token: "comment", foreground: "a0ada0" },
  { token: "number", foreground: "2f798a" },
  { token: "regexp", foreground: "ab5e3f" },
  { token: "identifier", foreground: "b07d48" },
  { token: "function", foreground: "59873a" },
  { token: "markup.heading", foreground: "8f8e8a", fontStyle: "bold" },
  { token: "markup.raw", foreground: "8f8e8a" },
  { token: "markup.quote", foreground: "2e808f" },
  { token: "markup.italic", fontStyle: "italic" },
  { token: "markup.bold", fontStyle: "bold" },
];

const vitesseDarkRules: editor.ITokenThemeRule[] = [
  { token: "keyword.operator", foreground: "cb7676" },
  { token: "keyword", foreground: "d5d5d3" },
  { token: "constant.language.boolean", foreground: "d5d5d3" },
  { token: "constant.language", foreground: "d5d5d3" },
  { token: "constant.numeric", foreground: "4C9A91" },
  { token: "constant", foreground: "c99076" },
  { token: "string.regexp", foreground: "c4704f" },
  { token: "string.comment", foreground: "758575dd" },
  { token: "string", foreground: "c98a7d" },
  { token: "support.type.builtin", foreground: "cb7676" },
  { token: "support.type", foreground: "5DA994" },
  { token: "support.constant", foreground: "c99076" },
  { token: "support", foreground: "b8a965" },
  { token: "storage.type", foreground: "cb7676" },
  { token: "storage", foreground: "cb7676" },
  { token: "entity.name.function", foreground: "80a665" },
  { token: "entity.name.tag", foreground: "d5d5d3" },
  { token: "entity.name.type", foreground: "5DA994" },
  { token: "entity.name", foreground: "80a665" },
  { token: "entity.other.attribute-name", foreground: "bd976a" },
  { token: "variable.language", foreground: "c99076" },
  { token: "variable", foreground: "bd976a" },
  { token: "type.identifier", foreground: "6872ab" },
  { token: "type", foreground: "5DA994" },
  { token: "attribute.value", foreground: "c98a7d" },
  { token: "attribute.name", foreground: "b8a965" },
  { token: "meta.property-name", foreground: "b8a965" },
  { token: "meta.object-literal.key", foreground: "b8a965" },
  { token: "meta.module-reference", foreground: "d5d5d3" },
  { token: "property", foreground: "b8a965" },
  { token: "namespace", foreground: "db889a" },
  { token: "delimiter.bracket", foreground: "666666" },
  { token: "delimiter", foreground: "666666" },
  { token: "operator", foreground: "cb7676" },
  { token: "tag", foreground: "d5d5d3" },
  { token: "comment", foreground: "758575dd" },
  { token: "number", foreground: "4C9A91" },
  { token: "regexp", foreground: "c4704f" },
  { token: "identifier", foreground: "bd976a" },
  { token: "function", foreground: "80a665" },
  { token: "markup.heading", foreground: "d5d5d3", fontStyle: "bold" },
  { token: "markup.raw", foreground: "d5d5d3" },
  { token: "markup.quote", foreground: "5d99a9" },
  { token: "markup.italic", fontStyle: "italic" },
  { token: "markup.bold", fontStyle: "bold" },
];

const vitesseLightTheme: editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  colors: {
    "editor.background": "#f4f1ea",
    "editor.foreground": "#1a1a1a",
    "editorLineNumber.foreground": "#1a1a1a50",
    "editorLineNumber.activeForeground": "#52504b",
    "editor.lineHighlightBackground": "#ece8df",
    "editor.selectionBackground": "#3784ff24",
    "editor.inactiveSelectionBackground": "#3784ff14",
    "editor.selectionHighlightBackground": "#3784ff14",
    "editor.foldBackground": "#3784ff10",
    "editorIndentGuide.background": "#00000012",
    "editorIndentGuide.activeBackground": "#00000028",
    "editorWhitespace.foreground": "#00000012",
    "editor.findMatchBackground": "#9a7b1a44",
    "editor.findMatchHighlightBackground": "#9a7b1a33",
    "editorBracketMatch.background": "#3784ff20",
    "editor.wordHighlightBackground": "#3784ff10",
    "editor.wordHighlightStrongBackground": "#3784ff1f",
    "editorWidget.background": "#ffffff",
    "editorStickyScroll.background": "#ece8df",
    "editorStickyScrollHover.background": "#ece8df",
  },
  rules: vitesseLightRules,
};

const vitesseDarkTheme: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  colors: {
    "editor.background": "#0c0c0c",
    "editor.foreground": "#f0f0ee",
    "editorLineNumber.foreground": "#f0f0ee50",
    "editorLineNumber.activeForeground": "#c9c9c6",
    "editor.lineHighlightBackground": "#141414",
    "editor.selectionBackground": "#69a3ff33",
    "editor.inactiveSelectionBackground": "#69a3ff1c",
    "editor.selectionHighlightBackground": "#69a3ff1c",
    "editor.foldBackground": "#69a3ff14",
    "editorIndentGuide.background": "#ffffff12",
    "editorIndentGuide.activeBackground": "#ffffff28",
    "editorWhitespace.foreground": "#ffffff12",
    "editor.findMatchBackground": "#f0b10033",
    "editor.findMatchHighlightBackground": "#f0b10022",
    "editorBracketMatch.background": "#69a3ff28",
    "editor.wordHighlightBackground": "#69a3ff14",
    "editor.wordHighlightStrongBackground": "#69a3ff24",
    "editorWidget.background": "#171717",
    "editorStickyScroll.background": "#141414",
    "editorStickyScrollHover.background": "#141414",
  },
  rules: vitesseDarkRules,
};

export function defineWorkspaceMonacoThemes(
  monaco: typeof import("monaco-editor"),
) {
  monaco.editor.defineTheme(workspaceMonacoThemeLight, vitesseLightTheme);
  monaco.editor.defineTheme(workspaceMonacoThemeDark, vitesseDarkTheme);
}
