import type { editor } from "monaco-editor";

export const workspaceMonacoThemeLight = "vitesse-light";
export const workspaceMonacoThemeDark = "vitesse-dark";

const vitesseLightRules: editor.ITokenThemeRule[] = [
  { token: "keyword.operator", foreground: "ab5959" },
  { token: "keyword", foreground: "8f8e8a" },
  { token: "constant.language.boolean", foreground: "8f8e8a" },
  { token: "constant.language", foreground: "8f8e8a" },
  { token: "constant.numeric", foreground: "2f798a" },
  { token: "constant", foreground: "a65e2b" },
  { token: "string.regexp", foreground: "ab5e3f" },
  { token: "string.comment", foreground: "a0ada0" },
  { token: "string", foreground: "b56959" },
  { token: "support.type.builtin", foreground: "ab5959" },
  { token: "support.type", foreground: "2e8f82" },
  { token: "support.constant", foreground: "a65e2b" },
  { token: "support", foreground: "998418" },
  { token: "storage.type", foreground: "ab5959" },
  { token: "storage", foreground: "ab5959" },
  { token: "entity.name.function", foreground: "59873a" },
  { token: "entity.name.tag", foreground: "8f8e8a" },
  { token: "entity.name.type", foreground: "2e8f82" },
  { token: "entity.name", foreground: "59873a" },
  { token: "entity.other.attribute-name", foreground: "b07d48" },
  { token: "variable.language", foreground: "a65e2b" },
  { token: "variable", foreground: "b07d48" },
  { token: "type.identifier", foreground: "5a6aa6" },
  { token: "type", foreground: "2e8f82" },
  { token: "attribute.value", foreground: "b56959" },
  { token: "attribute.name", foreground: "998418" },
  { token: "meta.property-name", foreground: "998418" },
  { token: "meta.object-literal.key", foreground: "998418" },
  { token: "meta.module-reference", foreground: "8f8e8a" },
  { token: "property", foreground: "998418" },
  { token: "namespace", foreground: "b05a78" },
  { token: "delimiter.bracket", foreground: "999999" },
  { token: "delimiter", foreground: "999999" },
  { token: "operator", foreground: "ab5959" },
  { token: "tag", foreground: "8f8e8a" },
  { token: "comment", foreground: "a0ada0" },
  { token: "number", foreground: "2f798a" },
  { token: "regexp", foreground: "ab5e3f" },
  { token: "identifier", foreground: "b07d48" },
  { token: "function", foreground: "59873a" },
  { token: "markup.heading", foreground: "8f8e8a", fontStyle: "bold" },
  { token: "markup.raw", foreground: "8f8e8a" },
  { token: "markup.quote", foreground: "2e808f" },
  { token: "markup.italic", fontStyle: "italic" },
  { token: "markup.bold", fontStyle: "bold" },
];

const vitesseDarkRules: editor.ITokenThemeRule[] = [
  { token: "keyword.operator", foreground: "cb7676" },
  { token: "keyword", foreground: "d5d5d3" },
  { token: "constant.language.boolean", foreground: "d5d5d3" },
  { token: "constant.language", foreground: "d5d5d3" },
  { token: "constant.numeric", foreground: "4C9A91" },
  { token: "constant", foreground: "c99076" },
  { token: "string.regexp", foreground: "c4704f" },
  { token: "string.comment", foreground: "758575dd" },
  { token: "string", foreground: "c98a7d" },
  { token: "support.type.builtin", foreground: "cb7676" },
  { token: "support.type", foreground: "5DA994" },
  { token: "support.constant", foreground: "c99076" },
  { token: "support", foreground: "b8a965" },
  { token: "storage.type", foreground: "cb7676" },
  { token: "storage", foreground: "cb7676" },
  { token: "entity.name.function", foreground: "80a665" },
  { token: "entity.name.tag", foreground: "d5d5d3" },
  { token: "entity.name.type", foreground: "5DA994" },
  { token: "entity.name", foreground: "80a665" },
  { token: "entity.other.attribute-name", foreground: "bd976a" },
  { token: "variable.language", foreground: "c99076" },
  { token: "variable", foreground: "bd976a" },
  { token: "type.identifier", foreground: "6872ab" },
  { token: "type", foreground: "5DA994" },
  { token: "attribute.value", foreground: "c98a7d" },
  { token: "attribute.name", foreground: "b8a965" },
  { token: "meta.property-name", foreground: "b8a965" },
  { token: "meta.object-literal.key", foreground: "b8a965" },
  { token: "meta.module-reference", foreground: "d5d5d3" },
  { token: "property", foreground: "b8a965" },
  { token: "namespace", foreground: "db889a" },
  { token: "delimiter.bracket", foreground: "666666" },
  { token: "delimiter", foreground: "666666" },
  { token: "operator", foreground: "cb7676" },
  { token: "tag", foreground: "d5d5d3" },
  { token: "comment", foreground: "758575dd" },
  { token: "number", foreground: "4C9A91" },
  { token: "regexp", foreground: "c4704f" },
  { token: "identifier", foreground: "bd976a" },
  { token: "function", foreground: "80a665" },
  { token: "markup.heading", foreground: "d5d5d3", fontStyle: "bold" },
  { token: "markup.raw", foreground: "d5d5d3" },
  { token: "markup.quote", foreground: "5d99a9" },
  { token: "markup.italic", fontStyle: "italic" },
  { token: "markup.bold", fontStyle: "bold" },
];

const vitesseLightTheme: editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  colors: {
    "editor.background": "#f6f6f6",
    "editor.foreground": "#2f2f2e",
    "editorLineNumber.foreground": "#2f2f2e50",
    "editorLineNumber.activeForeground": "#4a4a48",
    "editor.lineHighlightBackground": "#ebebea",
    "editor.selectionBackground": "#8f8e8a24",
    "editor.inactiveSelectionBackground": "#8f8e8a14",
    "editor.selectionHighlightBackground": "#8f8e8a14",
    "editor.foldBackground": "#8f8e8a10",
    "editorIndentGuide.background": "#00000015",
    "editorIndentGuide.activeBackground": "#00000030",
    "editorWhitespace.foreground": "#00000015",
    "editor.findMatchBackground": "#e6cc7744",
    "editor.findMatchHighlightBackground": "#e6cc7766",
    "editorBracketMatch.background": "#8f8e8a20",
    "editor.wordHighlightBackground": "#8f8e8a05",
    "editor.wordHighlightStrongBackground": "#8f8e8a10",
    "editorWidget.background": "#fbfbfa",
    "editorStickyScroll.background": "#ebebea",
    "editorStickyScrollHover.background": "#ebebea",
  },
  rules: vitesseLightRules,
};

const vitesseDarkTheme: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  colors: {
    "editor.background": "#141516",
    "editor.foreground": "#e4e4e2ee",
    "editorLineNumber.foreground": "#e4e4e250",
    "editorLineNumber.activeForeground": "#c9c9c6",
    "editor.lineHighlightBackground": "#1d1d1c",
    "editor.selectionBackground": "#d5d5d330",
    "editor.inactiveSelectionBackground": "#d5d5d318",
    "editor.selectionHighlightBackground": "#d5d5d318",
    "editor.foldBackground": "#d5d5d314",
    "editorIndentGuide.background": "#ffffff15",
    "editorIndentGuide.activeBackground": "#ffffff30",
    "editorWhitespace.foreground": "#ffffff15",
    "editor.findMatchBackground": "#e6cc7722",
    "editor.findMatchHighlightBackground": "#e6cc7744",
    "editorBracketMatch.background": "#d5d5d320",
    "editor.wordHighlightBackground": "#d5d5d310",
    "editor.wordHighlightStrongBackground": "#d5d5d320",
    "editorWidget.background": "#171819",
    "editorStickyScroll.background": "#1d1d1c",
    "editorStickyScrollHover.background": "#1d1d1c",
  },
  rules: vitesseDarkRules,
};

export function defineWorkspaceMonacoThemes(
  monaco: typeof import("monaco-editor"),
) {
  monaco.editor.defineTheme(workspaceMonacoThemeLight, vitesseLightTheme);
  monaco.editor.defineTheme(workspaceMonacoThemeDark, vitesseDarkTheme);
}
