export const TIPC_CHANNELS = [
  "appSetLanguage",
  "chatsArchive",
  "chatsArchivedDelete",
  "chatsArchivedDeleteImpact",
  "chatsArchivedList",
  "chatsArchivedRestore",
  "chatsCreate",
  "chatsDeleteAll",
  "chatsGet",
  "chatsList",
  "chatsLoad",
  "chatsPrewarm",
  "chatsRename",
  "chatsRuntimeConfig",
  "chatsSetMode",
  "chatsSetPermissionMode",
  "chatsSetRuntime",
  "chatsShowContextMenu",
  "chatSend",
  "agentsCreateCustom",
  "agentsCustomDeleteImpact",
  "agentsDeleteCustom",
  "agentsListAvailable",
  "agentsListCustom",
  "agentsUpdateCustom",
  "projectsChooseDirectory",
  "projectsGitStatus",
  "projectsCreate",
  "projectsDelete",
  "projectsGet",
  "projectsList",
  "projectsSearchFiles",
  "projectsShowContextMenu",
  "projectsUpdate",
  "workspaceToolsFileTree",
  "workspaceToolsGitDiff",
  "workspaceToolsGitCommit",
  "workspaceToolsReadFile",
  "workspaceToolsWriteFile",
] as const;

export type TipcChannel = (typeof TIPC_CHANNELS)[number];

export const TIPC_CHANNEL_SET: ReadonlySet<string> = new Set(TIPC_CHANNELS);
