import type { Automation } from "@/features/schedule/schedule-model";

export const scheduleFixture: Automation[] = [
  {
    agentLabel: "Current agent",
    cron: "0 9 * * *",
    enabled: true,
    id: "dependency-audit",
    name: "Daily dependency audit",
    nextRunAt: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    notifyOnFailure: true,
    projectId: "angel-engine",
    projectName: "angel-engine",
    prompt:
      "Audit dependency updates and security advisories. Summarize only actionable changes.",
    runs: [
      {
        durationSeconds: 94,
        id: "audit-run-1",
        startedAt: "2026-08-09T01:00:00.000Z",
        status: "succeeded",
        trigger: "scheduled",
      },
      {
        id: "audit-run-2",
        startedAt: "2026-08-08T01:00:00.000Z",
        status: "missed",
        trigger: "scheduled",
      },
    ],
    scheduleLabel: "Every day at 09:00",
    status: "active",
  },
  {
    agentLabel: "Current agent",
    cron: "*/30 * * * *",
    enabled: true,
    id: "ci-heartbeat",
    name: "CI heartbeat",
    nextRunAt: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
    notifyOnFailure: true,
    projectId: "angel-engine",
    projectName: "angel-engine",
    prompt: "Check CI and report only failures or jobs that appear stuck.",
    runs: [
      {
        durationSeconds: 38,
        error: "Desktop typecheck failed in workspace-page-view.tsx",
        id: "heartbeat-run-1",
        startedAt: "2026-08-09T15:30:00.000Z",
        status: "failed",
        trigger: "scheduled",
      },
      {
        durationSeconds: 31,
        id: "heartbeat-run-2",
        startedAt: "2026-08-09T15:00:00.000Z",
        status: "succeeded",
        trigger: "scheduled",
      },
    ],
    scheduleLabel: "Every 30 minutes",
    status: "failing",
  },
  {
    agentLabel: "Current agent",
    cron: "0 2 * * *",
    enabled: false,
    id: "nightly-tests",
    name: "Nightly test sweep",
    notifyOnFailure: true,
    prompt: "Run the test suite and summarize failures with likely owners.",
    runs: [],
    scheduleLabel: "Every day at 02:00",
    status: "paused",
  },
];
